import type { Workout } from "./types";

// Hand-built workouts used for manual export testing in third-party tools
// (see docs/export-testing.md). Ids and timestamps are fixed so generated
// files are reproducible; each fixture isolates one export feature.

const createdAt = "2026-07-01T00:00:00.000Z";
const updatedAt = "2026-07-01T00:00:00.000Z";

export const exportTestFixtures: Workout[] = [
  {
    id: "fixture-steady",
    name: "Fixture Steady Blocks",
    description: "Back-to-back steady targets with no ramps or ranges.",
    category: "tempo",
    ftp: 200,
    blocks: [
      {
        id: "steady-1",
        type: "steady",
        label: "Tempo",
        targetMode: "single",
        durationSeconds: 10 * 60,
        targetPercentFTP: 80,
      },
      {
        id: "steady-2",
        type: "recovery",
        label: "Easy spin",
        targetMode: "single",
        durationSeconds: 5 * 60,
        targetPercentFTP: 50,
      },
      {
        id: "steady-3",
        type: "steady",
        label: "Tempo again",
        targetMode: "single",
        durationSeconds: 10 * 60,
        targetPercentFTP: 85,
      },
    ],
    cues: [],
    createdAt,
    updatedAt,
  },
  {
    id: "fixture-ramps",
    name: "Fixture Ramps",
    description: "Ramped warmup and cooldown around a steady middle.",
    category: "endurance",
    ftp: 200,
    blocks: [
      {
        id: "ramp-warmup",
        type: "warmup",
        label: "Warmup ramp",
        targetMode: "ramp",
        durationSeconds: 10 * 60,
        startPercentFTP: 45,
        endPercentFTP: 75,
      },
      {
        id: "ramp-steady",
        type: "steady",
        label: "Endurance",
        targetMode: "single",
        durationSeconds: 20 * 60,
        targetPercentFTP: 68,
      },
      {
        id: "ramp-cooldown",
        type: "cooldown",
        label: "Cooldown ramp",
        targetMode: "ramp",
        durationSeconds: 10 * 60,
        startPercentFTP: 65,
        endPercentFTP: 40,
      },
    ],
    cues: [],
    createdAt,
    updatedAt,
  },
  {
    id: "fixture-ranges",
    name: "Fixture Ranges",
    description: "Range targets that exercise the low, midpoint, and high export strategies.",
    category: "sweet-spot",
    ftp: 200,
    blocks: [
      {
        id: "range-1",
        type: "steady",
        label: "Sweet spot range",
        targetMode: "range",
        durationSeconds: 15 * 60,
        minPercentFTP: 88,
        maxPercentFTP: 94,
      },
      {
        id: "range-recovery",
        type: "recovery",
        label: "Recovery range",
        targetMode: "range",
        durationSeconds: 5 * 60,
        minPercentFTP: 45,
        maxPercentFTP: 55,
      },
      {
        id: "range-2",
        type: "steady",
        label: "Threshold range",
        targetMode: "range",
        durationSeconds: 10 * 60,
        minPercentFTP: 95,
        maxPercentFTP: 105,
      },
    ],
    cues: [],
    createdAt,
    updatedAt,
  },
  {
    id: "fixture-repeats",
    name: "Fixture Repeats",
    description: "Repeat blocks with work and float children.",
    category: "vo2",
    ftp: 200,
    blocks: [
      {
        id: "repeat-warmup",
        type: "warmup",
        label: "Warmup",
        targetMode: "ramp",
        durationSeconds: 8 * 60,
        startPercentFTP: 45,
        endPercentFTP: 70,
      },
      {
        id: "repeat-set",
        type: "repeat",
        label: "VO2 set",
        repeatCount: 5,
        children: [
          {
            id: "repeat-on",
            type: "steady",
            label: "VO2 on",
            targetMode: "single",
            durationSeconds: 3 * 60,
            targetPercentFTP: 112,
          },
          {
            id: "repeat-off",
            type: "recovery",
            label: "Float",
            targetMode: "single",
            durationSeconds: 3 * 60,
            targetPercentFTP: 55,
          },
        ],
      },
      {
        id: "repeat-cooldown",
        type: "cooldown",
        label: "Cooldown",
        targetMode: "single",
        durationSeconds: 5 * 60,
        targetPercentFTP: 45,
      },
    ],
    cues: [],
    createdAt,
    updatedAt,
  },
  {
    id: "fixture-cues",
    name: "Fixture Cues",
    description: "Text cues that should appear as COURSE TEXT events.",
    category: "threshold",
    ftp: 200,
    blocks: [
      {
        id: "cues-warmup",
        type: "warmup",
        label: "Warmup",
        targetMode: "single",
        durationSeconds: 5 * 60,
        targetPercentFTP: 55,
        cues: [
          {
            id: "cue-settle",
            atSeconds: 30,
            text: "Settle into a smooth cadence",
            durationSeconds: 10,
          },
        ],
      },
      {
        id: "cues-work",
        type: "steady",
        label: "Threshold block",
        targetMode: "single",
        durationSeconds: 15 * 60,
        targetPercentFTP: 98,
        cues: [
          { id: "cue-hold", atSeconds: 60, text: "Hold steady just under FTP", durationSeconds: 15 },
          { id: "cue-halfway", atSeconds: 7 * 60 + 30, text: "Halfway there", durationSeconds: 10 },
        ],
      },
      {
        id: "cues-cooldown",
        type: "cooldown",
        label: "Cooldown",
        targetMode: "single",
        durationSeconds: 5 * 60,
        targetPercentFTP: 45,
        cues: [{ id: "cue-done", atSeconds: 60, text: "Nice work, spin it out", durationSeconds: 10 }],
      },
    ],
    cues: [],
    createdAt,
    updatedAt,
  },
  {
    id: "fixture-long",
    name: "Fixture Long Ride",
    description: "Over four hours of endurance to exercise the long-workout warning.",
    category: "endurance",
    ftp: 200,
    blocks: [
      {
        id: "long-warmup",
        type: "warmup",
        label: "Warmup",
        targetMode: "ramp",
        durationSeconds: 15 * 60,
        startPercentFTP: 45,
        endPercentFTP: 65,
      },
      {
        id: "long-steady",
        type: "steady",
        label: "All-day endurance",
        targetMode: "single",
        durationSeconds: 4 * 60 * 60,
        targetPercentFTP: 65,
      },
      {
        id: "long-cooldown",
        type: "cooldown",
        label: "Cooldown",
        targetMode: "single",
        durationSeconds: 10 * 60,
        targetPercentFTP: 45,
      },
    ],
    cues: [],
    createdAt,
    updatedAt,
  },
  {
    id: "fixture-special-name",
    name: "Fixture Café Crémeux #1 (60')!",
    description: "Name & description with accents, symbols — and emoji 🚴.",
    category: "recovery",
    ftp: 200,
    blocks: [
      {
        id: "special-steady",
        type: "steady",
        label: "Easy hour",
        targetMode: "single",
        durationSeconds: 60 * 60,
        targetPercentFTP: 55,
      },
    ],
    cues: [],
    createdAt,
    updatedAt,
  },
];
